### ISSUE TITLE
As an Approver I want a clickable link in the body of any booking status update notification email that opens the booking tool in a web browser.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#182]
if there’s no longer a way to link directly to the Admin page but it’s convenient to have a link in the notification emails that gets you to the tool quickly so if nothing else let's just link to the root of the Google Site.

the Google Site url is different for each deployment so we’ll need to set it up as another environment variable.

**Comment by lucia-gomez** [comment]
Added a link that opens the site based on the current site URL

https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/3617c51c-5eed-42fc-b7a0-e773ac95c694

**Comment by nopivnick** [comment]
I'm only seeing this on notification emails with status = REQUESTED. it should be on every email notification.

also, the link leads directly to the Apps Script url but I think it should probably go to the Google Site in which the Apps Script is embedded.

**Comment by lucia-gomez** [comment]
will update the url it goes to. But this task says it should be on approver emails, is that still the case or do we want it on EVERY email notification, even those going to requestors? Or on every email going to approvers?

**Comment by nopivnick** [comment]
@lucia-gomez given we plan to make requests editable, might as well make it every email going to both requestors and approvers.
