### ISSUE TITLE
As Samantha I want every request to be issued an incremental request number so I can easily reference specific requests.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#206]
# Bookings page(s) - Lucia

TODO:

- [x] add a "Request #" column
- [x] make the "Request #" column sortable

# Database - Riho

TODO:

- [x] every booking request should add a `requestNum` to its corresponding document in the db

# Notification emails - Riho and/or Lucia

TODO:

- [x] Subject heading pattern: `[Env] STATUS » Media Commons Request # 1: "Title"`

**Comment by lucia-gomez** [comment]
I'm thinking we should wait on this one until the DB migration is complete, since we could repurpose DB ID numbers for this. @rlho 
what do you think?

**Comment by nopivnick** [comment]
@lucia-gomez not sure if this changes your assessment but she wants incremental request numbers.

**Comment by rlho** [comment]
@nopivnick 
We already have IDs that firestore is automatically grading. Can we use it?

**Comment by rlho** [comment]
@nopivnick 
It's UID(they call document Id), you can see on firestore,

![Image](https://github.com/user-attachments/assets/c4db0d5c-4cec-4fbd-9b97-2047dca53d56)

**Comment by nopivnick** [comment]
@rlho yeah, unfortunately those UIDs are too complex. Samantha needs something simple like Request # 1, 2, 3, etc.

I'm guessing the backend will need to keep track of something like `lastRequestNum` and the app will need to increment++ it for every newly submitted request and write that value to a `requestNum` field.

**Comment by rlho** [comment]
@nopivnick 
 Firestore best practices advise against using such IDs, so I'd prefer to avoid them. However, if it's necessary, we can implement it.
https://firebase.google.com/docs/firestore/best-practices

**Comment by nopivnick** [comment]
my reading of that documentation is they recommend not to use incrementing numbers as *document IDs* but I'm not suggesting that, rather we have a *new* field thats `requestNum`. it's really just a label, it isn't used in db operations.

**Comment by rlho** [comment]
I added requestNumber to a booking collection
https://github.com/ITPNYU/booking-app/pull/340/files#diff-1d1290d7dd09a7dc4aa7914763cb8002b3c7ba8e2b3a7d1a1599440790913fbaR68
