### ISSUE TITLE
Bug: data validation on Attendance field in the request form should check for >= 1.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#229]

**Comment by Kaibanda** [comment]
I have issued a pull request to my branch named "Kai". Let me know if this can be merged with the main branch. Thanks.

**Comment by nopivnick** [comment]
@Kaibanda see [this comment](https://github.com/ITPNYU/mc-reservation-tool/pull/237#issuecomment-2189428529).

**Comment by lucia-gomez** [comment]
Yeah, absolutely nothing related to the UI refactor should be merged to main. You can develop on your personal dev branch and then submit a PR to merge that to the refactorUi branch

**Comment by Kaibanda** [comment]
I will ask about merging with the refator Ui branch instead of the main branch. Thank you. Should I redo my pull request to my personal dev branch?
