### ISSUE TITLE
BUG: UI: Admin page » Bookings » Other Info should show all details of the booking, not just the info that isn't displayed on the page.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#256]
![Image](https://github.com/user-attachments/assets/1b1c3f55-da04-483c-9a9c-746c304be38b)

**Comment by lucia-gomez** [comment]
![Image](https://github.com/user-attachments/assets/32d9a20f-16ed-41c3-af08-ef3b90ac29dc)
![Image](https://github.com/user-attachments/assets/001d5269-6648-4261-83b9-e370d3c20a80)
