### ISSUE TITLE
UI: The PA context should have a Booking tab same as the Admin context's Booking tab

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#260]
Bookings tab in Admin context:

![Image](https://github.com/user-attachments/assets/cdadb0be-8d09-4022-ae7c-03ad68e8e13f)

No Bookings tab in PA context:

![Image](https://github.com/user-attachments/assets/bfa38ef1-7ce1-4967-a375-99c77f26c6c1)

**Comment by lucia-gomez** [comment]
are you sure? The PA view only has that one tab. Do we think we'll add more tabs there or is this purely for consistency with Admin?

**Comment by nopivnick** [comment]
@lucia-gomez yes to both.
