### ISSUE TITLE
UI: Admin context » Bookings tab text edits

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#261]
- [ ] change "Dates" heading → "Date / Time"
- [ ] change "ID" heading → "Requestor"
- [ ] change "Contacts" heading → "Contact Info"
- [ ] change "Other Info" → "Details"
- [ ] in the "ID" column, display netID first, then name

![Image](https://github.com/user-attachments/assets/a14f0128-a7ea-44f7-8519-e9d1e7ea7170)

**Comment by lucia-gomez** [comment]
done 

![Image](https://github.com/user-attachments/assets/2ba54809-2ce1-4a7e-b552-655ba168ef89)
