### ISSUE TITLE
UI: "Status", "Dates", "Department/Role" and "ID" headings on the Bookings tab should be clickable and sort booking rows accordingly.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#262]
![Image](https://github.com/user-attachments/assets/390e0420-a17e-48f6-8787-349e1325b51d)

**Comment by lucia-gomez** [comment]
Are we sure we should be able to sort by Status? There's already the status chips that we can filter by. Would sorting by status just sort the statuses alphabetically?

**Comment by nopivnick** [comment]
yes, we should be able to sort filtered results by status.

either we sort alphabetically or we sort by approval status chronology. I'm thinking alphabetically, what do you think?

Approved
Canceled
Checked In
Declined
No Show
Pre-approved
Requested

or

Requested
Declined
Pre-approved
Approved
Canceled
Checked In
No Show
