### ISSUE TITLE
UI: Polish

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#265]
# Title Bar

TODO:

- [x] title bar should indicate the environment.

![Image](https://github.com/user-attachments/assets/4d7e6742-5d3f-4690-9974-5e74b177e567)

![Image](https://github.com/user-attachments/assets/fabeaeda-2270-4b4d-a49e-ec8d68354585)

# My Bookings

TODO:

- [x] welcome message should have the same CSS as the message banner in the rest of the app

![Image](https://github.com/user-attachments/assets/7cfd3a2f-cc3f-40b1-aae0-fe471c685b6a)

# Calendar

TODO:

- [x] message banner should fill the space between the Back and Next buttons
- [x] message banner should be obnoxious florescent green w/ 'auto-approval eligible' message or florescent orange w/ 'approval required' message
- [x] elapsed time should be gray

![Image](https://github.com/user-attachments/assets/199046c7-0709-4772-8637-760cc780d1dc)

# Booking Details Form

TODO:

- [x] CSS should be the same as the self-identify form (border, centered in screen, etc.)
- [x] "Your Request" section should display hour and minute but not seconds under time.
- [x] "Media Services" section should have a Yes/No toggle same as room setup, catering, and security sections which defaults to No and only shows options when toggled to Yes.

![Image](https://github.com/user-attachments/assets/e7a6f3d2-854c-4f54-abe5-b29a63954d17)

![Image](https://github.com/user-attachments/assets/f50decd9-549b-4121-a252-9e819a613013)

**Comment by lucia-gomez** [comment]
Can you clarify "welcome message should have the same CSS as the message banner in the rest of the app"? Should this be on the obnoxious green banner, non-bold text, etc?

Also are you sure the green/orange message banner should fill the whole space?... it hurts my design-y eyes to see that banner not line up with the edge of the calendar UI. It doesn't hurt my eyes to make it expand towards the Next button on the right, though

**Comment by nopivnick** [comment]
> Should this be on the obnoxious green banner, non-bold text, etc?

yes. also, let's lose the emoji and have the message just be "Welcome." for now.

> Also are you sure the green/orange message banner should fill the whole space?

I'm sure. I hope your deign-y eyes can forgive me.
