### ISSUE TITLE
As a user I want the booking request details form to limit the maximum length in the Title field to 40 characters so the text doesn't get cut off in the Bookings table.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#290]
![Image](https://github.com/user-attachments/assets/5a63736b-c790-439a-b946-7f8d6cbfe26f)

**Comment by lucia-gomez** [comment]
I made it so if you hover over the title it shows the whole thing, even if its too long to fit in the view. Also there's no guarantee that 40 characters won't be cut off on different screen sizes. Should I still set this limit?

**Comment by nopivnick** [comment]
I do think it would be good to prohibit people from writing out a novella as a title. more to the point, it can be difficult to read the title of an approved booking request in the Google Calendar context, especially if it includes multiple rooms. I wonder whether it should be even fewer than 40 characters?

what do you think?

**Comment by lucia-gomez** [comment]
sure we can set to 40 character limit for now and see how it goes
