### ISSUE TITLE
As an end-user I want the UI to communicate when a request has *not* successfully posted to the server.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#304]
![Image](https://github.com/user-attachments/assets/b2001b2f-77e5-47fa-88de-74c49560a89f)

**Comment by lucia-gomez** [comment]
![Image](https://github.com/user-attachments/assets/dfae55f6-b0d3-4d80-97df-760773a20de6)

**Comment by nopivnick** [comment]
nice!
