### ISSUE TITLE
As an Admin or PA user I want to be able to change the status of a booking to `CHECKED OUT` so we can capture a timestamp denoting when a client has concluded their booking.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#329]
# UI

TODO:

- [x] add "CHECKED OUT" to list of actions that can be taken in the Admin » Bookings and PA » Bookings tabs

# Backend

TODO:

- [x] add `Checked Out` to Status Type

**Comment by lucia-gomez** [comment]
>  add logic that automatically changes booking Status to Checked Out at endTime

This might be a big lift. It involves the app independently taking actions which we haven't done before... some script would have to repeatedly run at regular intervals to check if any bookings have ended. Or at the time a booking is approved, we schedule a job to run in the future at the booking's endTime. Either way seems like this will require integrating more GCP tools. I'm afraid to say it but I know GAS lets you schedule jobs like this

**Comment by nopivnick** [comment]
> It involves the app independently taking actions

it's alive!

> some script would have to repeatedly run at regular intervals to check if any bookings have ended

all our time slots are in 30 minute intervals so maybe we use [Cloud Scheduler](https://cloud.google.com/scheduler) to run a cron job on the :00 and :30 of every operational hour to check for any `status = Checked In` bookings and change them to `status = Checked Out` if `endTime - currentTime <= 0`?

**Comment by nopivnick** [comment]
on a side note, I'm starting to wonder whether each booking has two statuses, one for the request (REQUESTED, PRE-APPROVED, APPROVED, CANCELLED) and one for the requestor (CHECKED IN, NO SHOW, CHECKED OUT)?

**Comment by rlho** [comment]
Do we really need to automate the check-out process? As Lucia says, we'd need to consider and implement another middleware, which could take time to use and test it.
To release this application this month, how about having PAs manually change the status, just like with other statuses for now?
We could add the feature to automatically change actions after the semester begins.

**Comment by nopivnick** [comment]
@rlho 

> how about having PAs manually change the status, just like with other statuses for now?

yes, that's fine. I'll remove the todo item.

**Comment by lucia-gomez** [comment]
![Image](https://github.com/user-attachments/assets/c745eae1-af2a-4687-8499-865391a46e6a)
