### ISSUE TITLE
As a PA and Admin user I want an "Equip. Checkout" column in PA » Bookings and Admin » Bookings with an In/Out toggle button so I can keep track of equipment inventory.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#360]
If the request does not include/involve equipment, the toggle button should not appear.

**Comment by lucia-gomez** [comment]
https://github.com/user-attachments/assets/947cbb8f-5b6d-4ac8-b7fd-e0695ab7222a

**Comment by nopivnick** [comment]
@lucia-gomez sorry, I should have specified but can we add the equipment coulmn with toggle to the Admin » Bookings page as well?
