### ISSUE TITLE
BUG: N-number field in booking details form is missing data validation.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#364]
regex = `N[0-9]{8}`

**Comment by lucia-gomez** [comment]
it works for me and that regex is in the form already

https://github.com/user-attachments/assets/daed27ce-abba-4837-81c7-fed3d2e01e55

**Comment by nopivnick** [comment]
I'm able to submit an N-number with more than 8 digits (clearly my regex needs fixing).

![Image](https://github.com/user-attachments/assets/40053711-8ef8-44eb-ae93-c2669436aa0d)

![Image](https://github.com/user-attachments/assets/4e75c177-7d74-4775-a99f-39edb63ed1ef)

![Image](https://github.com/user-attachments/assets/89e2eb7c-8d39-4771-979b-00c33b65c79b)
