### ISSUE TITLE
BUG: Spaces in the calendar picker are doubled.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#376]
![Image](https://github.com/user-attachments/assets/5fe3b58a-54bc-4078-9971-ce3b93297fd0)

note there are duplicative entries in the `(default)` db:

![Image](https://github.com/user-attachments/assets/65da6258-bf0f-4f98-a141-9953582b1e2b)

**Comment by nopivnick** [comment]
@rlho did this happen because you accidentally imported twice? is it okay to just delete the duplicates in the db? do the UIDs of documents in the `rooms` collection get used somewhere else in the db? for what it's worth, as of this writing the `(default)` db hasn't recorded any bookings.

**Comment by rlho** [comment]
@nopivnick It was probably a duplicate entry due to something accidental. This can be fixed by deleting the duplicate from the database.
