### ISSUE TITLE
As Samantha I want to brand the booking app with the Media Commons mascot.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#382]
![Image](https://github.com/user-attachments/assets/a89382fd-9d4d-41bc-98b0-9cf2fcb6d457)

https://drive.google.com/drive/folders/13i4eJJAZ9V0C8y2ezAHpYcBYuGxKs3uU

**Comment by lucia-gomez** [comment]
![Image](https://github.com/user-attachments/assets/972f9ff3-4a6e-4a97-a8d9-3b9ee225e144)

**Comment by lucia-gomez** [comment]
i changed the SVG's shade of purple slightly to match our theme... let me know if I should change it back. It stood out a lot when it was a different shade of purple
