### ISSUE TITLE
URGENT: BUG: App is displaying booking details in the Calendar on `Prod`.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#397]
![Image](https://github.com/user-attachments/assets/220a8689-876a-4ddb-9217-397eeb236ae8)

**Comment by rlho** [comment]
@nopivnick 
we have logic to hide details for reservations made through our app, but we didn't include logic to hide details for other reservations.

**Comment by nopivnick** [comment]
@riho ah! can we amend the logic so it applies to events placed on the calendar directly?

**Comment by lucia-gomez** [comment]
changed all existing events to just say "Unavailable", regardless of title format or status

![Image](https://github.com/user-attachments/assets/f65449af-bff0-43bd-90a8-146e1186790c)
