### ISSUE TITLE
UX/UI: Reduce width of details modal

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#403]
![Image](https://github.com/user-attachments/assets/cc1674ff-d012-4af7-8073-a4cf7070f82a)

**Comment by lucia-gomez** [comment]
is this done?

**Comment by Greenfishyy** [comment]
Hi Lucia,

I didn’t make updates in the figma after our meeting. The top purple part I
need to add, the rest was final.

Lucy
