### ISSUE TITLE
As an Admin I want DECLINED to be a terminal status so that a DECLINED booking can't have it's status changed to APPROVED (via links in email notifications).

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#448]
![Image](https://github.com/user-attachments/assets/f77a96d5-ae0f-4646-8933-af1fb228ed0d)

**Comment by lucia-gomez** [comment]
this no longer applies with the recent approval/decline link refactor right?

**Comment by nopivnick** [comment]
@lucia-gomez you are correct.
