### ISSUE TITLE
Automatic approval logic

### ISSUE THREAD

**Issue by rlho** [ITPNYU/booking-app#72]
Requests will the following criteria will be automatically approved:

- 4 hours or less
- No Room setup
- No Security
- No Catering
- No Media Services
- No staffing

**Comment by rlho** [comment]
We can approve their conditions booking automatically.
- No Room setup
- No Security
- No Catering
- Media Services

@ss12430 What do you think about it?

**Comment by ss12430** [comment]
Writing down what we talked about yesterday- should also include:

No Media Commons Staffing (Including Audio Tech for 230 Audio Lab, and
Audio Tech and Lighting Tech for 103 Garage)



On Tue, Dec 12, 2023 at 11:43 AM Riho Takagi ***@***.***>
wrote:

> We can approve their conditions booking automatically.
>
>    - No Room setup
>    - No Security
>    - No Catering
>    - No Media Services
>
> @ss12430
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ss12430&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hvLPERRD5qd65mOdX297GA&m=gsI4NdOsNp_NU8lroUVtXg1FsozkhQlcW6wyVqVEOYk8rHJuGLIvFDiDh04kL_FQ&s=qxJGQCOflKnVTn4GhzQbiCCwxU4iOSJxiWY9RRwN09o&e=>
> What do you think about it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ITPNYU_mc-2Dreservation-2Dtool_issues_72-23issuecomment-2D1852412756&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hvLPERRD5qd65mOdX297GA&m=gsI4NdOsNp_NU8lroUVtXg1FsozkhQlcW6wyVqVEOYk8rHJuGLIvFDiDh04kL_FQ&s=Xoe3kn0F0ux7JJ9sCFyDu7WCzTnr_e3zigU3KlpPHvs&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKKAKOCCH6IHSN6QEVDETXLYJCCT3AVCNFSM6AAAAABARYZL4OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJSGQYTENZVGY&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hvLPERRD5qd65mOdX297GA&m=gsI4NdOsNp_NU8lroUVtXg1FsozkhQlcW6wyVqVEOYk8rHJuGLIvFDiDh04kL_FQ&s=1DKmgddP1w0x4frQrb_g5jix6zCiUw0SekWKzB8kGHQ&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
*Samantha Renshi Skinner (she/her)*
Director of Operations
370 Jay Street #515
O: (212) 998-2380 ext 82380
***@***.***
***@***.***

**Comment by lucia-gomez** [comment]
Additional requirement: no equipment requests. This falls under "no media service"

**Comment by rlho** [comment]
@lucia-gomez I currently include the condition that there is no Media Service available. Did you happen to have bugs about this?

**Comment by lucia-gomez** [comment]
Yes we had a bug about this exact issue, someone requested equipment and it was auto approved

**Comment by rlho** [comment]
Hmmm, I sent a request with the same conditions that caused the bug before, it was not auto-approved.

**Comment by lucia-gomez** [comment]
I made some recent changes that might have fixed it, are you working on top of main?
