### ISSUE TITLE
As an Admin user I want to click on a Final Approver settings tab on the Admin page so I can edit the Final Approver's email address in-app.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#87]
https://github.com/ITPNYU/mc-reservation-tool/blob/d65ad9fc7b879e791fd6195909477a4914ad8bda/media_commons_booking_app/src/server/admin.js#L3C1-L3C1

**Comment by lucia-gomez** [comment]
https://github.com/user-attachments/assets/88e88456-224d-4b50-ba38-2465863d0d9e

**Comment by lucia-gomez** [comment]
this is almost done, the UI updates the email in the DB. Just need @rlho to make the backend use this email rather than the hardcoded variable in our codebase when she has time
