### ISSUE TITLE
As an Admin user I want to click on a "Departments" tab on the Admin page and set stakeholder tier to Primary, Secondary, or Tertiary.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/booking-app#95]
the Department field should be a dropdown that pulls from a list of NYU departments and the Stakeholder Tier should be a dropdown menu with the tier types.

**Comment by nopivnick** [comment]
@rlho are you going to finish this by tomorrow?

**Comment by Kaibanda** [comment]
Do we want a department with a specific stakeholder associated to it and a tier assigned to them, or do we want a department itself, with all associated stakeholders, to have a tier?

**Comment by nopivnick** [comment]
@Kaibanda the departments are the stakeholders. it's two columns: the department and its corresponding stakeholder tier. it should look similar to the liaisons screen Lucia is building on her [refactorUi](https://github.com/ITPNYU/mc-reservation-tool/tree/refactorUi) branch.

![image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/43dd8dac-36a2-4ea7-9f8b-a4a90d4c4b9a)

**Comment by Kaibanda** [comment]
Ok, thank you for confirming. I will begin working on this on a separate branch based on the refactorUI branch.

**Comment by Kaibanda** [comment]
![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/144280311/7109a560-35c2-4800-abee-c4806b3a2608)

I currently have this for the Departments tab, and I also have some backend integration in place, though I think that we will need a tab on our spreadsheet for this to work properly. I would like to have my changes reviewed to see if this is on the right track. Please let me know how I can show my changes. Thank you

**Comment by Kaibanda** [comment]
![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/144280311/a3a02eaf-32b4-47bf-988a-47868f009f05)

I have further integrated the departments tab, and it now shows no results through being connected to the ListTable function. I want to review this code with either Riho or Lucia to go over how I can fix this bug that happens when I click on the "Admin users" tab.



![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/144280311/adda19fa-bfe0-4b2b-92fe-17d82166a4de)

I think this may have something to do with the spreadsheet not having a departments tab, but let me know what you think. Thank you.

**Comment by Kaibanda** [comment]
I actually just restarted the project and it does not cause any errors anymore. Let me know @rlho or @lucia-gomez if you can review the changes I've made with me. Thank you.

**Comment by Kaibanda** [comment]
This task is completed. Where should I make a pull request?

**Comment by nopivnick** [comment]
> This task is completed. Where should I make a pull request?
> 

@Kaibanda did you review your changes with @rlho offline first?

**Comment by Kaibanda** [comment]
I will do this next. I sent an email a couple of hours ago about working from home next week. Is it possible for me to do this so I can review this task as necessary before the Fall semester starts? Let me know. Thank you.

**Comment by lucia-gomez** [comment]
merged to main + sorted departments list alphabetically
